# Generated by Django 4.2.7 on 2023-12-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=16)),
                ('roll1', models.CharField(max_length=18)),
                ('roll2', models.CharField(max_length=18)),
                ('roll3', models.CharField(max_length=18)),
                ('roll4', models.CharField(max_length=18)),
                ('roll5', models.CharField(max_length=18)),
                ('spodify', models.CharField(max_length=1000)),
                ('instgram', models.CharField(max_length=1000)),
                ('discord', models.CharField(max_length=1000)),
                ('btc', models.CharField(max_length=300)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
